### PR TITLE
Hide the controls on first render and fix autoplaying not working on IOS after a re-render

### PR DESCRIPTION
**Pull request by batusai513**
This PR adds the ability to hide all the video controls on first render.

### CODE REVIEW

**Comment by kylemilloy** [comment]
Good additions here...lemme review quick for testing but this should be a no brainer add.

I'm a little fuzzy on class props in JS classes...would we be better off using a getter function instead of a class prop for backwards compatibility?

Getter
```js
static defaultProps() {
    return {
        key: 'val'
    };
}
```

Class prop
```js
static defaultProps = {
    key: 'val'
}
```

I seem to remember that the former worked in babel whereas the latter required a babel plugin to function...

**Comment by batusai513** [comment]
@kylemilloy Interesting, shamefully, i don't so much experience with `defaultProps` as getter function, but i know that if we want full compatibility we can attach the `defaultProps` object to the class itself:

```js
export default class VideoControls extends Component {}
VideoControls.defaultProps = {
  key: 'val'
};
```
What do you think?

**Comment by kylemilloy** [comment]
Naaahh...I don't think it needs to be *that* backwards compatible. We can assume the user is using some form of babel...besides, I think we'd have to use prototype for this case as it's a class, no?

Anyways...all of that doesn't matter...I tested this out and it works fine...I'm going to go ahead and add it in...thanks again for the commit. This is a good addition.

**Comment by batusai513** [comment]
👍 no problem, i'm more than glad to help, and thanks to you for the component on the first place 🥇

**Pull request merged**
