### PR TITLE
Fix the problem of RTL direction when I18nManager.isRTL

### PR DESCRIPTION
**Pull request by rastegars**
When the I18nManager is set to rtl, all the components inside `<VideoPlayer>` are aligned along the right side and the seekbar circle is moving from right to left. also the gestures doesn't work correctly. I've fixed this problem and set the direction of all component to LTR. Now it looks the same regardless of whether I18nManager is set to RTL

### CODE REVIEW

**Comment by kylemilloy** [comment]
Hmmm...I don't speak arabic so can't say for sure but do we have to flip the whole interface? Seems to me because it's all icon based we're just have to flip the title view, no?

**Comment by rastegars** [comment]
Have you tried to force RTL to see what happens?
```
import { I18nManager } from 'react-native';
I18nManager.forceRTL(true);
```
When you do this, you need to reload the app to apply the changes. following that, all the components including progress bar, timer, play/pause button and volume slider are right aligned which is not a correct function in both RTL and LTR. Also the gestures of volume slider and progress bar are malfunctioning. In Persian, Arabic, Hebrew and other RTL writing systems, such things aren't usually right aligned. So we have to reverse all the components to set them to the normal direction (LTR). I did this by setting `flexDirection: 'row-reverse'` everywhere inside  `VideoPlayer`.

**Comment by kylemilloy** [comment]
Can you screenshot what your changes do in RTL so I can better understand? Or provide a fork where I can switch between LTR/RTL to see what you mean?

**Comment by rastegars** [comment]
screen shot 2018-10-20 at 2 59 16 am

**Comment by kylemilloy** [comment]
Rejecting this. I appreciate the work but at this time we're not planning to support full i18n in v2.

**Pull request closed without merging**
