### PR TITLE
Allow user to override the fullscreen state

### LINKED ISSUE #128: Fullscreen control not updated after closing the native iOS fullscreen
Hi @itsnubix,

Firstly, thanks for your work.

I was facing a bug happening when we are closing the fullscreen on iOS. The fullscreen control is not updated, even if we are using `onExitFullscreen` prop to manually trigger the fullscreen dismiss.

## Why it happens ?

In our case, the screen is closed, and we are triggering fullscreen exit (because for the user, it's the same action IMO), and we are not able to update the fullscreen control to tell it, that we changed our state.

To illustrate that issue, look at the top right fullscreen icon:

kapture 2019-01-24 at 16 51 18

## How to fix it ?

IMO we should be able to give to the video player a newer prop prop (ie: `isFullscreen`) to override that state.

## Steps to reproduce

Open your video in fullscreen on iOS, exit the native fullscreen mode with the `X` icon, and manually trigger a fullscreen exit with that:

```
const handleShrink = () => this.videoPlayer.player.ref.dismissFullscreenPlayer();

[...]

<VideoPlayer 
...
ref={() => (this.videoPlayer = ref)}
onExitFullscreen={handleShrink}
/>
```

### PR DESCRIPTION
**Pull request by VincentCATILLON**
This PR resolves #128

## Result and observation

You should be able to change the `isFullscreen` prop at runtime, and see the fullscreen control state change visually.

**Before**:

kapture 2019-01-24 at 16 51 18

**After**:

kapture 2019-01-24 at 16 49 51

## To test before and after

Refer to the issue `Steps to reproduce` section.

### CODE REVIEW

**Comment by VincentCATILLON** [comment]
Please refer to the detailed issue to understand

**Comment by ThomasStubbe** [comment]
When will this PR be merged?

**Comment by VincentCATILLON** [comment]
ping @kylemilloy

**Comment by kylemilloy** [comment]
Ping ping! Looks like you've added a lot to this than just fullscreen. ccControl, testID, etc...likely my fault as I've been away doing other things. There's some 16 commits to this...which is appreciated...but it's a lot to add all in one go. How can we break this up into smaller chunks?

**Comment by alexfigtree** [comment]
@VincentCATILLON Please resolve merge conflicts

**Comment by kodayashi** [comment]
@VincentCATILLON any luck here? I'm happy to address this PR to get this resolved (for the original issue), just let me know (and FYI @kylemilloy)

**Comment by kylemilloy** [comment]
@kodayashi - sure thing. I know this is a common ask. I'll close this if you wanna do your own that just addresses FS.

**Pull request closed without merging**
