### PR TITLE
feat: add typescript declaration.

### PR DESCRIPTION
**Pull request by kuasha420**
Hello, 

Thank you for the great library. I've added typescript declaration for it. 

Let me know if anything else needs changing.

Best Regards. 

Arafat

### CODE REVIEW

**Comment by GolfredoPerezFernandez** [comment]
nice

**Comment by kuasha420** [comment]
@itsnubix I've fixed the conflict. Can this get merged? 

Thanks.

**Comment by kylemilloy** [comment]
Bunch of questions here...firstly wth is a DuckNavigator lol.

**Comment by kuasha420** [comment]
@kylemilloy I'd be happy to answer all the questions you have. 

> firstly wth is a DuckNavigator lol.

This codebase only cares if the navigation object has a pop method and uses it. Many implementation of a navigator may have it, including @react-navigation/stack, react-native-screens/native-stack and react-native-navigation. So we only care of the passed navigation object has the pop method hence the DuckNavigator (reference to Duck Typing Practices). 

Regards.

**Review by jrhager84 — APPROVED** [review]
Can we please merge this?

**Comment by FezMLG** [comment]
@kylemilloy can you please marge this?

**Pull request merged**
