### PR TITLE
try to show the circle in the seekbar

### PR DESCRIPTION
**Pull request by azisuazusa**
This PR is related to issue #42 
I think this issue happened because the circle in the seek bar is not showing. So, in this PR I try to show it.

### CODE REVIEW

**Comment by pongponglau** [comment]
@azisuazusa, thanks a lot. I can see the circle again in Android after applying your changes. Good job.

**Comment by azisuazusa** [comment]
@pongponglau you're welcome

**Comment by kylemilloy** [comment]
Thanks for this. Been working on a lot of projects so haven't had the time to review. Will check it out sometime this week.

**Comment by pongponglau** [comment]
@azisuazusa, when i try in a read android device, the seek bar is not very responsively , i can only move the seek bar at the circle successfully one out of ten attempts. The volume bar has higher successful rate (perhaps the icon is bigger). May i ask how i can make the panresponder of the seek bar more responsive?

Thank you very much

**Comment by kylemilloy** [comment]
I've rebuilt the seekbar area completely and it will now show on Android (7.1.1 at least does) as well as iOS.

**Pull request closed without merging**
