### PR TITLE
- add fix to update styles on prop change

### PR DESCRIPTION
**Pull request by thetalonhughes**

### CODE REVIEW

**Comment by t-hughes** [comment]
fix for issue #122

**Comment by t-hughes** [comment]
@kylemilloy if this could go in as well as a minor version update to npmjs that would be dope. Also if you need help maintaining, I wouldn't mind taking a stab at it.

**Comment by thetalonhughes** [comment]
@kylemilloy any chance this could go in and a new minor version update along with it to npmjs?

**Comment by kylemilloy** [comment]
Done.

**Comment by thetalonhughes** [comment]
@kylemilloy thanks man, also as I mentioned, if you want, I may be able to find time to help maintain this. Would help me get better as a programmer as well.

**Pull request merged**
