### PR TITLE
New optional features: Live scrubbing and tap anywhere to toggle play/pause

### PR DESCRIPTION
**Pull request by EdTorbett**
Live scrubbing works by pausing the video while the seek bar is held and seeking within the video as the seek bar is moved. The minimum step between seeks (in milliseconds) is controlled by the value of the scrubbing property - I'm not sure if I've described this clearly enough in the README.md.

When tapAnywhereToPause is true, tapping onscreen will first show the controls, then as long as the controls are visible, subsequent single taps will toggle playing/paused instead. In this case the only way to hide the controls is to wait for controlTimeout to expire. Double taps will continue to toggle fullscreen as normal.

Both features are disabled by default so only changes to original behaviour are:
- 300ms delay before controls toggle (waiting to determine if tap or double-tap),
- Seeking can be initiated by pressing anywhere on the seek bar rather than having to accurately select the seek bar handle.

### CODE REVIEW

**Comment by EdTorbett** [comment]
I'm happy to split this into 2 PRs if desired.

An alternative implementation of tapAnywhereToPause would be to allow an onTap callback property to be supplied that overrides the default tap behaviour. However, this would not have access to enough state information to know whether the controls are currently visible, which is necessary to know whether to toggle the controls or to toggle pause.

**Comment by kylemilloy** [comment]
I'm sorry I haven't merged this sooner...seems like a really useful addition. If you can update the code to work with the latest releases I'll merge this in.

**Comment by EdTorbett** [comment]
> I'm sorry I haven't merged this sooner...seems like a really useful addition. If you can update the code to work with the latest releases I'll merge this in.

This should be updated now, but unfortunately due to the Covid-19 lockdown I don't have the tools to test it here! Luckily the merge conflicts were very minor changes so it looks like it'll work the same way.

**Comment by kylemilloy** [comment]
I’ll give it a shot. Thanks!

K. 

On May 18, 2020, at 04:17, Edward Torbett <notifications@github.com> wrote:

﻿


I'm sorry I haven't merged this sooner...seems like a really useful addition. If you can update the code to work with the latest releases I'll merge this in.

This should be updated now, but unfortunately due to the Covid-19 lockdown I don't have the tools to test it here! Luckily the merge conflicts were very minor changes so it looks like it'll work the same way.

**Comment by kylemilloy** [comment]
The 300ms wait is definitely pretty heavy...going to play around with the timing. And live scrubbing doesn't seem to cause as much issues as when we originally tested this....so good so far. Let me play with this a bit..

**Comment by EdTorbett** [comment]
> The 300ms wait is definitely pretty heavy...going to play around with the timing. And live scrubbing doesn't seem to cause as much issues as when we originally tested this....so good so far. Let me play with this a bit..

I was thinking this too when I fixed the merge requests this morning, so I made it configurable via a property, doubleTapTime. I've just realised I forgot to add this property to the README, so I've just done that now. Hopefully it takes some of the weight off the 300ms.

**Comment by kylemilloy** [comment]
Change the default to 130ms and I'll merge this in. :)

**Comment by EdTorbett** [comment]
Done!

**Pull request merged**
